import type { OneProviderAdapterDryRunReport } from "./dryRunReportTypes.js";
import { createOneProviderAdapterDryRunReport } from "./oneProviderAdapterDryRunReport.js";

const defaultCreatedAt = "2026-07-04T00:00:00.000Z";

export interface OneProviderAdapterDryRunCliInput {
  readonly explicit_opt_in?: string | boolean;
  readonly explicit_live_request?: string | boolean;
  readonly created_at?: string;
}

export interface OneProviderAdapterDryRunCliError {
  readonly code: string;
  readonly message: string;
}

export type OneProviderAdapterDryRunCliResult =
  | {
      readonly ok: true;
      readonly report: OneProviderAdapterDryRunReport;
      readonly process_env_read: false;
      readonly api_key_required: false;
    }
  | {
      readonly ok: false;
      readonly errors: readonly OneProviderAdapterDryRunCliError[];
      readonly process_env_read: false;
      readonly api_key_required: false;
    };

export function createOneProviderAdapterDryRunCliReport(
  input: OneProviderAdapterDryRunCliInput = {}
): OneProviderAdapterDryRunCliResult {
  const optIn = parseOptionalBoolean(input.explicit_opt_in, "explicit_opt_in");
  const liveRequest = parseOptionalBoolean(input.explicit_live_request, "explicit_live_request");
  const errors = [...optIn.errors, ...liveRequest.errors];

  if (errors.length > 0) {
    return {
      ok: false,
      errors,
      process_env_read: false,
      api_key_required: false
    };
  }

  return {
    ok: true,
    report: createOneProviderAdapterDryRunReport({
      report_id: "one_provider_adapter_dry_run_cli_report",
      harness_id: "default_disabled_one_provider_live_harness_scaffold",
      provider_adapter_id: "one_provider_adapter_skeleton",
      report_mode: "dry_run",
      explicit_opt_in: optIn.value,
      explicit_live_request: liveRequest.value,
      provider_output_shape_valid: false,
      created_at: input.created_at ?? defaultCreatedAt,
      notes: ["Generated by inert one-provider adapter dry-run CLI surface."]
    }),
    process_env_read: false,
    api_key_required: false
  };
}

function parseOptionalBoolean(
  value: string | boolean | undefined,
  field: "explicit_opt_in" | "explicit_live_request"
): { readonly value: boolean; readonly errors: readonly OneProviderAdapterDryRunCliError[] } {
  if (value === undefined) {
    return { value: false, errors: [] };
  }
  if (typeof value === "boolean") {
    return { value, errors: [] };
  }
  if (value === "true") {
    return { value: true, errors: [] };
  }
  if (value === "false") {
    return { value: false, errors: [] };
  }

  return {
    value: false,
    errors: [
      {
        code: `invalid_${field}`,
        message: `${field} must be true or false.`
      }
    ]
  };
}
