import type { HollowManifest } from "../../../types/hollow.js";

export const characterCountManifest = {
  hollow_id: "hollow.text.character_count",
  hollow_name: "Character Count Hollow",
  hollow_version: "1.0.0",
  schema_version: "1.0.0",
  category: "text",
  description: "Counts characters, lines, words, and newlines in provided text.",
  input_type: "character_count_input",
  input_schema_ref: "schemas/hollows/text/character-count.input.json",
  output_schema_ref: "schemas/hollows/text/character-count.output.json",
  permissions: ["none"],
  permissions_required: [],
  file_access_scope: "none",
  network_access: false,
  execution_mode: "local_deterministic",
  deterministic: true,
  deterministic_level: "strict",
  result_units: "characters",
  checks: ["input_text_present", "character_count_completed"],
  max_input_size: 100000,
  max_runtime_ms: 1000,
  supports_batching: false,
  supports_streaming: false,
  cache_policy: "input_digest",
  status: "trusted",
  owner: "caleb-ai-core"
} as const satisfies HollowManifest;

export const promptLimitManifest = {
  hollow_id: "hollow.text.prompt_limit",
  hollow_name: "Prompt Limit Hollow",
  hollow_version: "1.0.0",
  schema_version: "1.0.0",
  category: "text",
  description: "Checks whether text fits within a deterministic character limit.",
  input_type: "prompt_limit_input",
  input_schema_ref: "schemas/hollows/text/prompt-limit.input.json",
  output_schema_ref: "schemas/hollows/text/prompt-limit.output.json",
  permissions: ["none"],
  permissions_required: [],
  file_access_scope: "none",
  network_access: false,
  execution_mode: "local_deterministic",
  deterministic: true,
  deterministic_level: "strict",
  result_units: "characters",
  checks: ["input_text_present", "limit_valid", "prompt_limit_checked"],
  max_input_size: 100000,
  max_runtime_ms: 1000,
  supports_batching: false,
  supports_streaming: false,
  cache_policy: "input_digest",
  status: "draft",
  owner: "caleb-ai-core"
} as const satisfies HollowManifest;

export const sectionBalanceManifest = {
  hollow_id: "hollow.text.section_balance",
  hollow_name: "Section Balance Hollow",
  hollow_version: "1.0.0",
  schema_version: "1.0.0",
  category: "text",
  description: "Inspects bracketed text sections and reports counts, lengths, and missing or repeated sections.",
  input_type: "section_balance_input",
  input_schema_ref: "schemas/hollows/text/section-balance.input.json",
  output_schema_ref: "schemas/hollows/text/section-balance.output.json",
  permissions: ["none"],
  permissions_required: [],
  file_access_scope: "none",
  network_access: false,
  execution_mode: "local_deterministic",
  deterministic: true,
  deterministic_level: "strict",
  result_units: "sections",
  checks: ["input_text_present", "section_scan_completed"],
  max_input_size: 200000,
  max_runtime_ms: 1500,
  supports_batching: false,
  supports_streaming: false,
  cache_policy: "input_digest",
  status: "trusted",
  owner: "caleb-ai-core"
} as const satisfies HollowManifest;

export const repetitionScanManifest = {
  hollow_id: "hollow.text.repetition_scan",
  hollow_name: "Repetition Scan Hollow",
  hollow_version: "1.0.0",
  schema_version: "1.0.0",
  category: "text",
  description: "Detects repeated deterministic word and phrase n-grams in text.",
  input_type: "repetition_scan_input",
  input_schema_ref: "schemas/hollows/text/repetition-scan.input.json",
  output_schema_ref: "schemas/hollows/text/repetition-scan.output.json",
  permissions: ["none"],
  permissions_required: [],
  file_access_scope: "none",
  network_access: false,
  execution_mode: "local_deterministic",
  deterministic: true,
  deterministic_level: "strict",
  result_units: "phrases",
  checks: ["input_text_present", "repetition_scan_completed"],
  max_input_size: 200000,
  max_runtime_ms: 2000,
  supports_batching: false,
  supports_streaming: false,
  cache_policy: "input_digest",
  status: "trusted",
  owner: "caleb-ai-core"
} as const satisfies HollowManifest;

export const textHollowManifests = [
  characterCountManifest,
  promptLimitManifest,
  sectionBalanceManifest,
  repetitionScanManifest
] as const satisfies readonly HollowManifest[];
